name: Build and Analyze

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and SonarQube Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure a full clone for SonarQube analysis

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # Using 'temurin' as it is the updated distribution

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          sonar-project-key: your-project-key
          sonar-project-name: your-project-name
          sonar-project-version: '1.0'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Uncomment the following lines if you want to fail the job based on the Quality Gate
      # - name: Check SonarQube Quality Gate
      #   uses: sonarsource/sonarqube-quality-gate-action@v2
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
